# Generated by Django 5.2.6 on 2025-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
