# Generated by Django 5.2.6 on 2025-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0003_doctor_is_approved_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('once', 'Une seule fois'), ('daily', 'Tous les jours'), ('weekly', 'Toutes les semaines'), ('monthly', 'Tous les mois')], default='once', max_length=20),
        ),
    ]
